### ISSUE TITLE
Proposal: Single-Action epics receive third argument of all actions stream

### ISSUE THREAD

**Issue by ksaldana1** [AveroLLC/types-first-ui#13]
After thinking through the use cases I believe we should change the type signature of Single-Action epics to 

```typescript
(action$: Observable<TAction>, epicDeps?: TEpicDeps, actions$?: Observable<TAllActions>): Observable<TAllActions>
```

We were purposefully very restrictive in our original definition based mostly off the use cases in our application. However I think one obvious use case pokes some holes in it: cancellation.

One of the bigger selling points Observables have going for them is trivial cancellation with a variety of operators RxJS provides. However most of those operators rely on a "notifier" observable to trigger cancellation. In the context of a Redux application, this trigger would almost certainly be the emitting of another action (what else would it be, right?). Without this `actions$` stream, you lose a lot of the power of the declarative cancellation that RxJS provides.

The reason we did this was to avoid letting users do crazy stuff in single action epics. I think placing this as the third argument helps a bit from an API perspective, but perhaps we can do something like adding more `$` signs like angular 1 in the name to make people aware its slightly off course (tho I'm even waffling about that). 

The alternative is that any action that needs cancellation has to be forced through the "extraEpics" (we should think of a better name) pipeline. I think this would be a detriment to code readability and project organization. Wanting to cancel an epic with a single effect seems pretty average use. 

I am open to any opinions or suggestions on the topic.

**Comment by githop** [comment]
My 2 cents: What about something like

    (action$: Observable<TAction>, epicDeps?: TEpicDeps, cancelWhen$?: Observable<TAction>)

Where the third argument is a single notifier that you want to listen to for cancellation. Is it often the case that a user would need to listen to multiple sources to potentially cancel when any of them emit? (I see `countQueueStart` in FCM listens to two notifiers so my point may be moot). 

It would be cool if, for cancellation, all the user has to do is specify a third parameter and that is it. Similarly to how `ofType` is abstracted away in a single action epic, perhaps it could be possible to make it such that `takeUntil` is also abstracted away for them? The drawback is that it would disable the user from doing something after the cancellation, maybe it could either be an action or a callback, and if it's a callback you specify your own `takeUntil` logic (kinda like the interceptor in makeTrackedRequest)

I think that could be a good compromise in terms of discouraging the user to do crazy stuff for single action epics, and if the users needs more flexibility then they can go with the good old AllActionsEpic. 

As for names, what about something like "unary epic" and "variadic epic"?

I like this name because for a "unary epic" you don't have to bother with `ofType`, which itself is variadic, and using 'ofType' in a single action epic kinda encourages the user to want to specify more actions than the singular one they currently have access to.

**Comment by autoric** [comment]
@githop I'm not sure that makes sense? We are talking about the api for implementing action epics, so that 3rd parameters is not something that the consumer provides, it is something provided to them.  

Borrowing from the examples in our docs:
```
const addRequest = action(ActionTypes.ADD_REQUEST, {
  reducer: (state, action) => {
    return Paths.pendingRequest.set(true)(state);
  },
  epic: (action$, { counterAddSvc }) => {
    return action$.pipe(
      mergeMap(action => {
        // action inferred as {type: ActionTypes.ADD_REQUEST, payload: {tryAdd: number} }
        return counterAddSvc.add(action.payload.tryAdd).pipe(
          map(newCount => {
            // API call was successful
            return addSuccess.creator({ newCount });
          }),
          catchError(error => {
            // API call failed
            return addFail.creator({ error });
          })
        );
      })
    );
  },
});
```

This is a pretty standard use case for an epic where some initiating action `ADD_REQUEST` causes an http requests to go out, and result in a success or failure action depending on the result.

So cancellation is an obvious next step. In our apps today we have a few places where we actually do cancellation, and a bunch more where we could. Some of them are things like global timers or queueing for server-side syncs. These are actually global actions, and `extraEpics` feels appropriate for them.

The most obvious case is for cancelling server requests when I don't care anymore. As it stands I could do something simple like cancel any outstanding request if a new one comes in before the previous finishes...
```
epic: (action$, { counterAddSvc }) => {
    return action$.pipe(
      mergeMap(action => {
        // request, success, failure stuff...
      }),
      takeUntil(action$)
    );
  },
```
That's just an action cancelling itself.

But if I wanted to do something that depends on any other actions -the obvious example is a navigation away from the page or whatever - I have no view into the actions stream to do that. Right now that would have to go into the extraEpics, which definitely doesn't feel like the right place to put all your request actions.

**Comment by autoric** [comment]
I mulled it over last night, but I can't think of a better way to deal with this. I think providing all actions$ as a 3rd argument makes sense.
